name: Deploy application on AWS Elastic Beanstalk
on:
  push:
    branches: master
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
        
      - name: Create Deployment Package
        run: zip -r deploy.zip .

      - name: setting up AWS credentials
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.ACCESS_KEY }}
          aws_secret_key: ${{ secrets.SECRET_KEY }}
          application_name: Blog-app-EBS
          environment_name: Blog-app-EBS-env
          version_label: ${{ github.sha }}
          existing_bucket_name: elasticbeanstalk-ap-south-1-113553330435
          region: ap-south-1
          deployment_package: deploy.zip
          use_existing_version_if_available: "true"
